### ISSUE TITLE
Is it possible to provide a nuget package?

### ISSUE THREAD

**Issue by tinohager** [joaoportela/CircularBuffer-CSharp#18]
I found only some packages for ring buffer. It would be really great if we could also get your project via nuget.

https://www.nuget.org/packages?q=ring+buffer

**Comment by joaoportela** [comment]
I tried to keep this in a single file for easy deployment.

I'm not if it would take too much effort.

Thanks for the suggestion, I'll think about it.

**Comment by tinohager** [comment]
I search for an extensions mostly on nuget instead of browsing github. And if there is an update it is also easier to obtain it via nuget.

**Comment by joaoportela** [comment]
This is my first time publishing a nuget package.
Here it is: https://www.nuget.org/packages/CircularBuffer/

Any feedback would be appreciated.
