### ISSUE TITLE
Back() is wrong when _end is 0 and buffer is not full

### ISSUE THREAD

**Issue by metzsg** [joaoportela/CircularBuffer-CSharp#2]
When _end is 0, yet the buffer is not full (_size is not Capacity), Back() returns the wrong value.

For example, consider a buffer of capacity 8 where indices 4-7 are occupied.  _start would be 4, and _end would be 0.  But the current implementation of Back() loops around by subtracting one from _size when _end is 0.  This would put us at index 3, which is bad!

Here is the proper implementation:

```
public T Back()
{
	ThrowIfEmpty();
	// Was '_size', now 'Capacity'
	return _buffer[(_end != 0 ? _end : Capacity) - 1];
}
```

Thanks a lot for this useful data structure!

**Comment by joaoportela** [comment]
--edited--

Found it and fixed.

Also added this test:

```
        [Test]
        public void CircularBuffer_WithDifferentSizeAndCapacity_BackReturnsLastArrayPosition()
        {
            // test to confirm this issue does not happen anymore:
            // https://github.com/joaoportela/CircullarBuffer-CSharp/issues/2

            var buffer = new CircularBuffer<int>(5, new[] { 0, 1, 2, 3, 4 });

            buffer.PopFront(); // (make size and capacity different)

            Assert.That(buffer.Back(), Is.EqualTo(4));
        }
```
