### ISSUE TITLE
socket use case suggestions

### ISSUE THREAD

**Issue by ZombieLei** [joaoportela/CircularBuffer-CSharp#26]
- Hi, thanks for the CircularBuffer code.
- When I use CircularBuffer in my socket code,I have some new functionality needed from it.
# Use case: socket send byte buffer and receive byte buffer
## Description:
- I have a separate socket thread whose job is:
  - To send my application serialized bytes to socket from CircularBuffer_PendingSend
  - To receive bytes from socket to CircularBuffer_PendingRecv
- The socket is in unblock mode
  - Every loop I get bytes from CircularBuffer_PendingSend
    - ask socket to send
    - the send function returned immediately with bytes sent
    - remove sent bytes count from CircularBuffer_PendingSend
    - I could use `ToArray` function, but I want to eliminate unnecessary memory copy
    - My expectation code is as this:
    - 
    ```cs
    if(circularBuffer_pendingSend.IsEmpty)
    {
         // pending send buffer is empty, waiting for next loop cycle
         Thread.Sleep(5);
         return;
    }
    ArraySegment<bytes>[] segments = circularBuffer_pendingSend.ToArraySegments();
    int totalBytesSent = 0;
    foreach(var seg in segments)
    {
         if(seg.Count == 0)
         {
             break;
         }
         int bytesSent = socket.Send(seg.Array, seg.Offset, seg.Count);
         totalBytesSent += bytesSent;
         // socket kernel buffer is full, so stop sending
         if(bytesSent < seg.Count)
         {
              break;
         }
     }
     circularBuffer_pendingSend.PopFrontN(totalBytesSent);
     ```

  - Every loop cycle I receive bytes from socket and add them to CircularBuffer_PendingRecv back
    - My expectation code is as this:
    -
    ```cs
    // buf is bytes[], temporary recv buffer
    int bytesReceived = socket.Receive(buf);
    circularBuffer_pendingRecv.PushBackBuffer(buf, 0, bytesReceived);
    ```

**Comment by joaoportela** [comment]
Those are interesting suggestions... I'll implement them when I have a bit of free time.

If you need it "right now", make some methods public and do:
`var segments = new ArraySegment<T>[2] { ArrayOne(), ArrayTwo() };`
to get the array segments.

**Comment by joaoportela** [comment]
I've added ToArraySegments method. I've made sure the interface is compatible with `socket.Send` so that you can use it directly.
