### ISSUE TITLE
Not an iss-ue, a thank-you!

### ISSUE THREAD

**Issue by IsaMorphic** [joaoportela/CircularBuffer-CSharp#32]
Apologies in advance if this is the wrong place to put this kind of feedback.  

Thank you so much for making this!  I was searching all morning for a solid, modern .NET implementation of this classic data structure and stumbled upon yours right when I was about to give up and implement it myself.  I'm hoping to integrate the code I plan to use it in with my first proprietary software-based business endeavor, so the Unlicense is also much appreciated.  

My hat is off to you.  Cheers!

**Comment by joaoportela** [comment]
Thank you, this comment makes me feel appreciated.

I know this is just a fairly straightforward implementation, but it makes me happy that I've helped anyone. :)
