### ISSUE TITLE
[Question] Safe for multi-thread usage ?

### ISSUE THREAD

**Issue by fmg-lydonchandra** [joaoportela/CircularBuffer-CSharp#64]
Hi, this CircularBuffer-CSharp library is NOT safe for multi-thread usage, is it ?

There is no locking mechanism 

        public void PopFront()
        {
            ThrowIfEmpty("Cannot take elements from an empty buffer.");
            _buffer[_start] = default(T);
            Increment(ref _start);
            --_size;
        }

        private void Increment(ref int index)
        {
            if (++index == Capacity)
            {
                index = 0;
            }
        }

**Comment by joaoportela** [comment]
It is not safe for multi-thread usage, and unfortunately support will not be added.

I believe @naualex was building a version with multi-thread support.
You can see his code here: https://github.com/joaoportela/CircularBuffer-CSharp/pull/71
